# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ngame.proto\x12\x04grpc\"\t\n\x07Nothing\"\x10\n\x03Map\x12\t\n\x01s\x18\x01 \x01(\t\"9\n\x11PlayerInformation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0b\n\x03szx\x18\x02 \x01(\x05\x12\x0b\n\x03szy\x18\x03 \x01(\x05\"6\n\x0fGameInformation\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05\x66ield\x18\x03 \x01(\t\"2\n\x04Move\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06move_x\x18\x02 \x01(\x05\x12\x0e\n\x06move_y\x18\x03 \x01(\x05\"\x0f\n\x02Id\x12\t\n\x01s\x18\x01 \x01(\t\"*\n\x08Movement\x12\x0e\n\x06move_x\x18\x01 \x01(\x05\x12\x0e\n\x06move_y\x18\x02 \x01(\x05\"\x16\n\tDirection\x12\t\n\x01s\x18\x01 \x01(\t\"<\n\x0ePlayerMovement\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06move_x\x18\x02 \x01(\x05\x12\x0e\n\x06move_y\x18\x03 \x01(\x05\"+\n\nPlayerTurn\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdirection\x18\x02 \x01(\t\"\x1d\n\x10PlayersPositions\x12\t\n\x01s\x18\x01 \x01(\t2\xf4\x02\n\x04Game\x12\x31\n\x07\x43onnect\x12\x17.grpc.PlayerInformation\x1a\r.grpc.Nothing\x12\"\n\x06GetMap\x12\r.grpc.Nothing\x1a\t.grpc.Map\x12<\n\x13GetPlayersMovements\x12\r.grpc.Nothing\x1a\x14.grpc.PlayerMovement0\x01\x12\x34\n\x0fGetPlayersTurns\x12\r.grpc.Nothing\x1a\x10.grpc.PlayerTurn0\x01\x12,\n\x0fGetPlayersShots\x12\r.grpc.Nothing\x1a\x08.grpc.Id0\x01\x12%\n\x04Move\x12\x0e.grpc.Movement\x1a\r.grpc.Nothing\x12&\n\x04Turn\x12\x0f.grpc.Direction\x1a\r.grpc.Nothing\x12$\n\x04\x46ire\x12\r.grpc.Nothing\x1a\r.grpc.Nothingb\x06proto3')
)




_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='grpc.Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=29,
)


_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='grpc.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='grpc.Map.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=47,
)


_PLAYERINFORMATION = _descriptor.Descriptor(
  name='PlayerInformation',
  full_name='grpc.PlayerInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.PlayerInformation.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='szx', full_name='grpc.PlayerInformation.szx', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='szy', full_name='grpc.PlayerInformation.szy', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=106,
)


_GAMEINFORMATION = _descriptor.Descriptor(
  name='GameInformation',
  full_name='grpc.GameInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='grpc.GameInformation.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='grpc.GameInformation.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field', full_name='grpc.GameInformation.field', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=162,
)


_MOVE = _descriptor.Descriptor(
  name='Move',
  full_name='grpc.Move',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.Move.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_x', full_name='grpc.Move.move_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_y', full_name='grpc.Move.move_y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=214,
)


_ID = _descriptor.Descriptor(
  name='Id',
  full_name='grpc.Id',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='grpc.Id.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=231,
)


_MOVEMENT = _descriptor.Descriptor(
  name='Movement',
  full_name='grpc.Movement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='move_x', full_name='grpc.Movement.move_x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_y', full_name='grpc.Movement.move_y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=275,
)


_DIRECTION = _descriptor.Descriptor(
  name='Direction',
  full_name='grpc.Direction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='grpc.Direction.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=299,
)


_PLAYERMOVEMENT = _descriptor.Descriptor(
  name='PlayerMovement',
  full_name='grpc.PlayerMovement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.PlayerMovement.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_x', full_name='grpc.PlayerMovement.move_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_y', full_name='grpc.PlayerMovement.move_y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=361,
)


_PLAYERTURN = _descriptor.Descriptor(
  name='PlayerTurn',
  full_name='grpc.PlayerTurn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.PlayerTurn.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='grpc.PlayerTurn.direction', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=406,
)


_PLAYERSPOSITIONS = _descriptor.Descriptor(
  name='PlayersPositions',
  full_name='grpc.PlayersPositions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='grpc.PlayersPositions.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=437,
)

DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
DESCRIPTOR.message_types_by_name['Map'] = _MAP
DESCRIPTOR.message_types_by_name['PlayerInformation'] = _PLAYERINFORMATION
DESCRIPTOR.message_types_by_name['GameInformation'] = _GAMEINFORMATION
DESCRIPTOR.message_types_by_name['Move'] = _MOVE
DESCRIPTOR.message_types_by_name['Id'] = _ID
DESCRIPTOR.message_types_by_name['Movement'] = _MOVEMENT
DESCRIPTOR.message_types_by_name['Direction'] = _DIRECTION
DESCRIPTOR.message_types_by_name['PlayerMovement'] = _PLAYERMOVEMENT
DESCRIPTOR.message_types_by_name['PlayerTurn'] = _PLAYERTURN
DESCRIPTOR.message_types_by_name['PlayersPositions'] = _PLAYERSPOSITIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Nothing)
  })
_sym_db.RegisterMessage(Nothing)

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), {
  'DESCRIPTOR' : _MAP,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Map)
  })
_sym_db.RegisterMessage(Map)

PlayerInformation = _reflection.GeneratedProtocolMessageType('PlayerInformation', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERINFORMATION,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PlayerInformation)
  })
_sym_db.RegisterMessage(PlayerInformation)

GameInformation = _reflection.GeneratedProtocolMessageType('GameInformation', (_message.Message,), {
  'DESCRIPTOR' : _GAMEINFORMATION,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.GameInformation)
  })
_sym_db.RegisterMessage(GameInformation)

Move = _reflection.GeneratedProtocolMessageType('Move', (_message.Message,), {
  'DESCRIPTOR' : _MOVE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Move)
  })
_sym_db.RegisterMessage(Move)

Id = _reflection.GeneratedProtocolMessageType('Id', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Id)
  })
_sym_db.RegisterMessage(Id)

Movement = _reflection.GeneratedProtocolMessageType('Movement', (_message.Message,), {
  'DESCRIPTOR' : _MOVEMENT,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Movement)
  })
_sym_db.RegisterMessage(Movement)

Direction = _reflection.GeneratedProtocolMessageType('Direction', (_message.Message,), {
  'DESCRIPTOR' : _DIRECTION,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.Direction)
  })
_sym_db.RegisterMessage(Direction)

PlayerMovement = _reflection.GeneratedProtocolMessageType('PlayerMovement', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERMOVEMENT,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PlayerMovement)
  })
_sym_db.RegisterMessage(PlayerMovement)

PlayerTurn = _reflection.GeneratedProtocolMessageType('PlayerTurn', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERTURN,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PlayerTurn)
  })
_sym_db.RegisterMessage(PlayerTurn)

PlayersPositions = _reflection.GeneratedProtocolMessageType('PlayersPositions', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERSPOSITIONS,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:grpc.PlayersPositions)
  })
_sym_db.RegisterMessage(PlayersPositions)



_GAME = _descriptor.ServiceDescriptor(
  name='Game',
  full_name='grpc.Game',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=440,
  serialized_end=812,
  methods=[
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='grpc.Game.Connect',
    index=0,
    containing_service=None,
    input_type=_PLAYERINFORMATION,
    output_type=_NOTHING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetMap',
    full_name='grpc.Game.GetMap',
    index=1,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_MAP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayersMovements',
    full_name='grpc.Game.GetPlayersMovements',
    index=2,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_PLAYERMOVEMENT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayersTurns',
    full_name='grpc.Game.GetPlayersTurns',
    index=3,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_PLAYERTURN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlayersShots',
    full_name='grpc.Game.GetPlayersShots',
    index=4,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_ID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Move',
    full_name='grpc.Game.Move',
    index=5,
    containing_service=None,
    input_type=_MOVEMENT,
    output_type=_NOTHING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Turn',
    full_name='grpc.Game.Turn',
    index=6,
    containing_service=None,
    input_type=_DIRECTION,
    output_type=_NOTHING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Fire',
    full_name='grpc.Game.Fire',
    index=7,
    containing_service=None,
    input_type=_NOTHING,
    output_type=_NOTHING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAME)

DESCRIPTOR.services_by_name['Game'] = _GAME

# @@protoc_insertion_point(module_scope)
